version : '3'


services:
  web:
    build: .
    command: sudo python3 manage.py runserver 0.0.0.0:8000
    container_name: know_food_webapp
    volumes: 
      - .:/code
    ports:
      - "8000:8000"